Repository codemagic-ci-cd/cli-tools, pull requests merged in 2022-09, with the labels that each got.

#260 CI: Use M1 Mac minis for CI
  codemagic.yaml
Labels: CI

#263 Bugfix:
  CHANGELOG.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/scripts/code_signing_manager.rb
Labels: bug

#266 Feature: log project build settings
  CHANGELOG.md
  docs/xcode-project/README.md
  docs/xcode-project/build-ipa.md
  docs/xcode-project/show-build-settings.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/models/xcodebuild.py
  src/codemagic/tools/_xcode_project/arguments.py
  src/codemagic/tools/xcode_project.py
Labels: enhancement

#268 Dependencies: Set upper bound `<38.0.0` for `cyrptography` dependency
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/cli/argument/typed_cli_argument.py
  src/codemagic/tools/_app_store_connect/arguments.py
Labels: dependencies
