Repository codemagic-ci-cd/cli-tools, pull requests merged in 2022-10, with the labels that each got.

#271 Docs: Show exactly how to pass the custom export options JSON string to use-profiles
  src/codemagic/tools/_xcode_project/arguments.py
Labels: documentation

#274 Bugfix: Remove `assert` from `Certificate.from_p12`
  CHANGELOG.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/models/certificate.py
Labels: bug

#275 Dependencies: Regenerate `poetry.lock` with updated dependencies for development environments
  CHANGELOG.md
  poetry.lock
Labels: dependencies

#277 Bugfix: `xcode-project use-profiles` error message if `xcodeproj` Ruby gem is missing
  CHANGELOG.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/models/code_signing_settings_manager.py
Labels: bug, enhancement

#280 Bugfix: `xcode-project detect-bundle-id` fails with `KeyError`
  CHANGELOG.md
  src/codemagic/models/bundle_id_detector.py
Labels: bug
