Repository codemagic-ci-cd/cli-tools, pull requests merged in 2022-05, with the labels that each got.

#223 Improvement: `xcresult` test result parsing speedup
  CHANGELOG.md
  src/codemagic/__version__.py
  src/codemagic/cli/cli_process.py
  src/codemagic/models/xctests/xcresulttool.py
Labels: enhancement

#224 Feature: Add option to filter profiles by archive type for `xcode-project use-profiles`
  CHANGELOG.md
  docs/xcode-project/use-profiles.md
  src/codemagic/__version__.py
  src/codemagic/apple/resources/enums.py
  src/codemagic/cli/cli_app.py
  src/codemagic/google_play/resources/enums.py
  src/codemagic/models/__init__.py
  src/codemagic/models/enums.py
  src/codemagic/models/export_options.py
  src/codemagic/tools/_xcode_project/arguments.py
  src/codemagic/tools/xcode_project.py
  tests/models/enums/__init__.py
  tests/models/enums/test_resource_enum.py
  tests/models/test_export_options.py
  tests/tools/app_store_connect/arguments/test_beta_build_localizations.py
Labels: enhancement

#225 Dependencies: Update `pyOpenSSL` version requirement for development
  Pipfile
  Pipfile.lock
  src/codemagic/tools/keychain.py
Labels: dependencies

#226 Development: Add default values to all arguments in `add_certificates` and `use_profiles` declarations
  CHANGELOG.md
  src/codemagic/tools/keychain.py
  src/codemagic/tools/xcode_project.py
Labels: enhancement

#232 Bugfix: Update Xcode project bundle identifier resolving
  CHANGELOG.md
  bin/code_signing_manager.rb
Labels: bug
