Repository codemagic-ci-cd/cli-tools, pull requests merged in 2023-10, with the labels that each got.

#357 Bugfix: Support Apple Vision Pro device type
  CHANGELOG.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/apple/resources/enums.py
Labels: bug

#353 Add note that `--cancel-previous-submissions` does not work for TestFlight submissions
  CHANGELOG.md
  docs/app-store-connect/builds/submit-to-app-store.md
  docs/app-store-connect/publish.md
  src/codemagic/tools/_app_store_connect/arguments.py
Labels: documentation

#355 Add option to configure timeout for finding build from App Store Connect
  CHANGELOG.md
  docs/app-store-connect/publish.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/tools/_app_store_connect/actions/publish_action.py
  src/codemagic/tools/_app_store_connect/arguments.py
Labels: enhancement

#361 Fix Google Play release promotion
  CHANGELOG.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/google_play/resources/track.py
  tests/google_play/resources/test_track_resource.py
Labels: bug

#362 Update GitHb Action CI jobs
  .github/workflows/run-checks.yml
  CHANGELOG.md
Labels: CI

#365 Fix `UnicodeDecodeError` when looking for failures from Xcode build logs
  CHANGELOG.md
  src/codemagic/utilities/backwards_file_reader.py
  tests/utilities/test_backwards_file_reader.py
Labels: bug
