Repository codemagic-ci-cd/cli-tools, pull requests merged in 2023-06, with the labels that each got.

#317 Feature: Firebase releases
  .flake8
  CHANGELOG.md
  README.md
  docs/README.md
  docs/firebase-app-distribution/README.md
  docs/firebase-app-distribution/get-latest-build-version.md
  docs/firebase-app-distribution/releases.md
  docs/firebase-app-distribution/releases/list.md
  poetry.lock
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/apple/resources/resource.py
  src/codemagic/google/__init__.py
  src/codemagic/google/errors.py
  src/codemagic/google/firebase_client.py
  src/codemagic/google/google_client.py
  src/codemagic/google/resource_managers/__init__.py
  src/codemagic/google/resource_managers/mixins/__init__.py
  src/codemagic/google/resource_managers/mixins/acting_manager_mixin.py
  src/codemagic/google/resource_managers/mixins/listing_manager_mixin.py
  src/codemagic/google/resource_managers/release_manager.py
  src/codemagic/google/resource_managers/resource_manager.py
  src/codemagic/google/resources/__init__.py
  src/codemagic/google/resources/identifiers/__init__.py
  src/codemagic/google/resources/identifiers/app_identifier.py
  src/codemagic/google/resources/identifiers/resource_identifier.py
  src/codemagic/google/resources/release.py
  src/codemagic/google/resources/release_notes.py
  src/codemagic/google/resources/resource.py
  src/codemagic/tools/__init__.py
  src/codemagic/tools/firebase_app_distribution/__init__.py
  src/codemagic/tools/firebase_app_distribution/__main__.py
  src/codemagic/tools/firebase_app_distribution/action_groups/__init__.py
  src/codemagic/tools/firebase_app_distribution/action_groups/firebase_action_groups.py
  src/codemagic/tools/firebase_app_distribution/action_groups/releases_action_group.py
  src/codemagic/tools/firebase_app_distribution/actions/__init__.py
  src/codemagic/tools/firebase_app_distribution/actions/get_latest_build_version_action.py
  src/codemagic/tools/firebase_app_distribution/argument_types.py
  src/codemagic/tools/firebase_app_distribution/arguments.py
  src/codemagic/tools/firebase_app_distribution/errors.py
  src/codemagic/tools/firebase_app_distribution/firebase_app_distribution.py
  src/codemagic/tools/firebase_app_distribution/firebase_app_distribution_action.py
  src/codemagic/tools/firebase_app_distribution/resource_printer.py
  tests/google/__init__.py
  tests/google/conftest.py
  tests/google/test_firebase_client.py
  tests/google/test_live_firebase_client.py
  tests/tools/mocks/firebase_releases.json
  tests/tools/test_firebase_app_distribution.py
Labels: enhancement

#322 Dependencies: Update minumum `google-api-python-client` version
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/google/google_client.py
Labels: dependencies

#323 Bugfix: Do not require release notes for Firebase releases
  CHANGELOG.md
  src/codemagic/google/resources/release.py
Labels: bug

#326 Feature: Add decorator to mark functions as deprecated
  CHANGELOG.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/apple/app_store_connect/provisioning/bundle_ids.py
  src/codemagic/apple/resources/enums.py
  src/codemagic/utilities/decorators.py
  tests/apple/app_store_connect/provisioning/test_bundle_ids.py
  tests/utilities/decorators/__init__.py
  tests/utilities/decorators/test_deprecated.py
Labels: enhancement
