Repository codemagic-ci-cd/cli-tools, pull requests merged in 2025-02, with the labels that each got.

#444 Duplicate readme pages for action groups
  CHANGELOG.md
  doc.py
  docs/app-store-connect/app-store-version-localizations/README.md
  docs/app-store-connect/app-store-version-phased-releases/README.md
  docs/app-store-connect/app-store-version-submissions/README.md
  docs/app-store-connect/app-store-versions/README.md
  docs/app-store-connect/apps/README.md
  docs/app-store-connect/beta-app-review-submissions/README.md
  docs/app-store-connect/beta-build-localizations/README.md
  docs/app-store-connect/beta-groups/README.md
  docs/app-store-connect/builds/README.md
  docs/app-store-connect/bundle-ids/README.md
  docs/app-store-connect/certificates/README.md
  docs/app-store-connect/devices/README.md
  docs/app-store-connect/profiles/README.md
  docs/app-store-connect/review-submission-items/README.md
  docs/app-store-connect/review-submissions/README.md
  docs/firebase-app-distribution/releases/README.md
  docs/google-play/tracks/README.md
Labels: documentation

#445 Fix action documentation links in action group readme tables
  doc.py
  docs/app-store-connect/app-store-version-localizations/README.md
  docs/app-store-connect/app-store-version-phased-releases/README.md
  docs/app-store-connect/app-store-version-submissions/README.md
  docs/app-store-connect/app-store-versions/README.md
  docs/app-store-connect/apps/README.md
  docs/app-store-connect/beta-app-review-submissions/README.md
  docs/app-store-connect/beta-build-localizations/README.md
  docs/app-store-connect/beta-groups/README.md
  docs/app-store-connect/builds/README.md
  docs/app-store-connect/bundle-ids/README.md
  docs/app-store-connect/certificates/README.md
  docs/app-store-connect/devices/README.md
  docs/app-store-connect/profiles/README.md
  docs/app-store-connect/review-submission-items/README.md
  docs/app-store-connect/review-submissions/README.md
  docs/firebase-app-distribution/releases/README.md
  docs/google-play/tracks/README.md
Labels: documentation

#447 Fix `android-app-bundle build-apks` and `android-app-bundle build-universal-apk` actions
  CHANGELOG.md
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/shell_tools/bundletool.py
Labels: bug

#448 Make Androguard dependency optional for initial installation
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  src/codemagic/__version__.py
  src/codemagic/models/application_package/apk_package.py
  tests/models/application_package/test_apk_package.py
Labels: dependencies

#449 Bugfix: Pass correct keystore_password to jarsigner
  CHANGELOG.md
  src/codemagic/__version__.py
  src/codemagic/shell_tools/jarsigner.py
Labels: bug
